
env:
  Creds: ${{ secrets.AZURE_MAG1_CREDENTIALS }}
  SubscriptionID1: ${{ secrets.AZURE_MAG_SUB1 }}
  AzureCloudEnvironment:  'AzureUSGovernment'
  ResourceGroup1Name:  "KillerHomeLab-01"
  vnetName: 'khl-VNet3'
  vnetPrefix: '10.3.0.0/16'
  subnet1Name: 'khl-vnet3-subnet1'
  subnet1Prefix: '10.3.1.0/24'
  location: 'usgovvirginia'  
  
on: [push]
name: Deploy-VNet-and-NIC
jobs:
  Deploy-Resources:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: "${{env.Creds}}"
        environment: "${{env.AzureCloudEnvironment}}"

    - name: Deploy VNet
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: "${{env.Subscription1ID}}"
        resourceGroupName: "${{env.ResourceGroup1Name}}"
        template: "Deployments/Deploy-Virtual-Network/linkedtemplates/vnet.json"
        parameters:
          vnetName=${{env.vnetName}}
          vnetprefix=${{env.vnetPrefix}}
          subnet1Name=${{env.subnet1Name}}
          subnet1Prefix="${{env.subnet1Prefix}}"
          location="${{env.location}}"

    - name: Deploy NIC
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: "${{env.Subscription1ID}}"
        resourceGroupName: "${{env.ResourceGroup1Name}}"
        template: "Deployments/Deploy-Network-Interface-Card/linkedtemplates/networkinterface.json"
        parameters:
          computerName='khl-vm-01'
          vnetName=${{env.vnetName}}
          subnetName=${{env.subnet1Name}}
          location="${{env.location}}"          